_src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 60)]
    private $name;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $picture;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'datetime')]
    private $start_at;

    #[ORM\Column(type: 'datetime')]
    private $endAt;

    #[ORM\ManyToOne(targetEntity: Team::class, inversedBy: 'events')]
    private $team;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'userEvent')]
    private $user;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(\DateTimeInterface $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->endAt;
    }

    public function setEndAt(\DateTimeInterface $endAt): self
    {
        $this->endAt = $endAt;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->user->removeElement($user);

        return $this;
    }
}

_src/Entity/Hotnew.php
<?php

namespace App\Entity;

use App\Repository\HotnewRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HotnewRepository::class)]
class Hotnew
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 250)]
    private $title;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    #[ORM\Column(type: 'text')]
    private $content;

    #[ORM\Column(type: 'datetime')]
    private $create_at;

    #[ORM\Column(type: 'datetime')]
    private $publishAt;

    #[ORM\Column(type: 'boolean')]
    private $datetime;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $editAt;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $picture;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'hotnews')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getPublishAt(): ?\DateTimeInterface
    {
        return $this->publishAt;
    }

    public function setPublishAt(\DateTimeInterface $publishAt): self
    {
        $this->publishAt = $publishAt;

        return $this;
    }

    public function getDatetime(): ?bool
    {
        return $this->datetime;
    }

    public function setDatetime(bool $datetime): self
    {
        $this->datetime = $datetime;

        return $this;
    }

    public function getEditAt(): ?\DateTimeInterface
    {
        return $this->editAt;
    }

    public function setEditAt(?\DateTimeInterface $editAt): self
    {
        $this->editAt = $editAt;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\AdRepository;
use App\Repository\TeamRepository;
use App\Repository\UserRepository;
use App\Repository\EventRepository;
use App\Repository\HotnewRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    private $userRepository;
    private $teamRepository;
    private $adRepository;
    private $eventRepository;
    private $hotnewRepository;

    public function __construct(
        UserRepository $userRepository,
        TeamRepository $teamRepository,
        AdRepository $adRepository,
        EventRepository $eventRepository,
        HotnewRepository $hotnewRepository,
    ){
        $this->userRepository = $userRepository;
        $this->teamRepository = $teamRepository;
        $this->adRepository = $adRepository;
        $this->eventRepository = $eventRepository;
        $this->hotnewRepository = $hotnewRepository;
    }

    #[Route('/', name: 'main_index')]
    public function index(): Response
    {
        $users = $this->userRepository->findBy(array(),array('id' => 'DESC'),5 ,0);
        $teams = $this->teamRepository->findBy(array(),array('id' => 'DESC'),5 ,0);
        $ads = $this->adRepository->findBy(array(),array('id' => 'DESC'),5 ,0);
        $events = $this->eventRepository->findBy(array(),array('id' => 'DESC'),5 ,0);
        $hotnews = $this->hotnewRepository->findBy(array(),array('id' => 'DESC'),5 ,0);


        return $this->render('main/index.html.twig', [
            'users' => $users,
            'teams' => $teams,
            'ads' => $ads,
            'events' => $events,
            'hotnews' => $hotnews,
        ]);
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Gameet 
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/main/index.css') }}">
    
{% endblock %}




{% block mainClasses %}{% endblock %}

{% block body %}
    <div>
        <div>
            <h1 class="text-center">Bienvenue sur Gameet, n'ayez pas peur de jouer.</h1>
            <h2 class="text-center">Rejoignez nous !</h2>
           
            </a>
        </div>


        <br>
        <div>
            <div class="d-flex justify-content-center">
                <div class="text-center">
                  <div class="slider">
               <div class="images">
                <input type="radio" name="slide" id="img1">
                <input type="radio" name="slide" id="img2">
                <input type="radio" name="slide" id="img3">
                <img src="images\imgesports.jpeg" class="m1" alt="img1">
                <img src="images\imgjeu.jpeg"  class="m2"alt="img2">
                <img src="images\imggame.jpeg"  class="m3"   alt=" img3">
            </div>
                <div class="dots">
                    <label for="img1"></label>
                    <label for="img2"></label>
                  <label for="img3"></label>
                </div>
        </div>
           
        </div>

    
                

        
    </div>
</div>
{% for user in users %}
  
{% endfor %}
</div>
            
            <br>
            
            <div class="example-wrapper">
            <p>Derniers Joueurs inscrits:</p>
           
              <div class="ima">
              
                    <img src="images\img2.jpeg"  class="m2"alt="im2">
                    <img src="images\img3.jpeg"  class="m3"   alt=" im3">
                    <img src="images\img1.jpeg"  class="m2"alt="im2">
                    <img src="images\img4.jpeg"  class="m3"   alt=" im3">
                     </div>
                  
               
            </div>

        



                {% for team in teams %}
                <div>
                    <h2 class="card-title">{{ ad.name }}</h2>
                    <p class="card-text">{{ ad.description|slice(0, 80) }} ...</p>
                    <p>Ajouté par {{ ad.user.nickname }}</p> à h\\hi'</p>
                </div>
            {% endfor %}
            </div>
    
            <br>
            
            
            <p>Dernières Equipes inscrites:</p>
            
                
                     
                   <div class="ima">
                    <img src="images\team1.jpeg" class="t1" alt="image équipe fantôme">
                    <img src="images\team2.jpeg"  class="t2"alt="image équipe dragon">
                    <img src="images\team3.jpeg"  class="t3"   alt=" image  équipe aigle ">
                    <img src="images\team4.jpeg" class="t4" alt="image équipe bouffon">
                    <img src="images\team5.jpeg"  class="t5"alt="image équipe de joueurs">
          
                     </div>
                  
            </div>
               
            </div>
            
            {% for ad in ads %}
            <div>
                <h2 class="card-title">{{ ad.name }}</h2>
                <p class="card-text">{{ ad.description|slice(0, 80) }} ...</p>
                <p>Ajouté par {{ ad.user.nickname }}</p> à h\\hi'</p>
            </div>
        {% endfor %}
       
                  
        <p>Dernières annonces:</p>
    
    <div class="ima">

    <img src="images\ad1.jpeg" class="ad1" alt="image vente de jeu">
    <img src="images\ad2.jpeg" class="ad2" alt="image vente d'une xbox">
    <img src="images\ad3.jpeg" class="ad3" alt="image vente d'un  ">
    <img src="images\ad4.jpeg" class="ad4" alt="image vente de 2 manette de playstation">
   
   </div>
    


    <br>
 


                {% for event in events %}
          
                
                    <div>
                        <h2 class="card-title">{{ event.name }}</h2>
                        <p>Commence le : {{ event.startAt|date('d/m/Y à h\\hi') }}</p>
                        <p class="card-text">{{ event.description|slice(0, 80) }} ...</p>
                        <p>Fini le : {{ event.endAt|date('d/m/Y à h\\hi') }}</p>
                    </div>
                  
                   

                
                {% endfor %}

                <p>Derniers Evénements:</p>

                <div class="ima">
                    <img src="images\event1.jpeg" class="ev1" alt="image évenements mariokart">
                 
                    <img src="images\event2.jpeg"  class="ev2"alt="image événements joueurs">

                     <img src="images\event3.jpeg"  class="ev3"   alt=" image événements paris week game ">
                    
          
                     </div>
        

      
                
                {% for hotnew in hotnews %}
               
              
                        <h2 class="card-title">{{ hotnew.title }}</h2>
                        <p>Publié le {{ hotnew.publishAt|date('d/m/Y à h\\hi') }}</p>
                        <p class="card-text">{{ hotnew.content }}</p>
                        <p>Créé le {{ hotnew.createAt|date('d/m/Y à h\\hi') }}</p>
                        <p class="card-text">Ajouté par {{ hotnew.user.nickname }}</p>
                    </div>
                {% endfor %}
                <p>Dernières actualités</p>
                
                
                               
                    <div class="ima">

                <img src="images\imgnintendo.jpeg" class="a1" alt="ima1"><br>
                Nouvelle nintendo switch Oled!!
                <br>
                
            </div>
        </div>
    </div>
{% endblock %}